name: PR 检查

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: 为 gradlew 添加执行权限
      run: chmod +x gradlew.sh
      
    - name: 为生成密钥脚本添加执行权限
      run: chmod +x generate-keystore.sh
      
    - name: 生成签名密钥
      run: ./generate-keystore.sh
      
    - name: 构建调试版本 APK
      run: ./gradlew.sh assembleDebug
      
    - name: 上传调试版本 APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk